CREATE DATABASE product;

USE product;

CREATE TABLE menu(
ID_menu INT (50) NOT NULL AUTO_INCREMENT PRIMARY KEY,
menuname VARCHAR(50),
price VARCHAR(100),
menu_image BLOB
)ENGINE = INNODB;

ALTER TABLE menu MODIFY price INT;

DESCRIBE menu;

INSERT INTO menu VALUE (1, 'menu1', 30000, '');

SELECT*FROM menu;